# Generated by Django 5.1.5 on 2025-02-09 04:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0002_alter_user_username_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
